dist: trusty
language: node_js
node_js:
  - 8.9.1
cache:
  npm: false
branches:
  only:
    - master
# before_install:
#   - npm install -g webpack ftp chalk recursive-readdir-sync
# - npm link webpack ftp chalk recursive-readdir-sync
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  # script: bash ./deploy.sh
  # script: node ftpupload.js
  script: node deploy.js
  on:
    branch: master
