language: node_js
node_js:
  - 8.9.1
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm install -g webpack ftp chalk recursive-readdir-sync
script:
  - npm run build
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
