language: node_js
node_js:
  - 8.9.1
cache:
  directories:
    - node_modules
script:
  - npm run build
before_install:
  - npm install
deploy:
  provider: script
  script: node deploy.js
  on:
    branch: master
