dist: trusty
language: node_js
node_js:
  - 'stable'
branches:
  only:
    - master
# before_install:
#   - npm install -g webpack ftp chalk recursive-readdir-sync
#   - npm link webpack ftp chalk recursive-readdir-sync
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
after_script:
  - node afterScript.js
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  # script: node ftpupload.js
  # script: node deploy.js
  on:
    branch: master
